const PlacementData = [
    {
      driveId: "65f3a8d9c9b1f7a5b6d2e1f9",
      title: "Software Engineer Hiring Drive",
      companyName: "Tech Innovators Ltd.",
      companyType: "Product-Based",
      companyDescription:
        "Tech Innovators Ltd. is a leading software company specializing in AI and cloud computing solutions.",
      jobProfiles: [
        {
          index: 1,
          jobRole: "Software Engineer",
          aboutRole: "Responsible for developing scalable web applications.",
          location: "Bangalore, India",
          ctc: 1200000,
          baseSalary: 1000000,
          stipend: 50000,
          expectedJoiningDate: "2025-07-01",
          eligibility: {
            program: "B.Tech",
            year: 2025,
            eligibleBranches: ["CSE", "IT", "ECE"],
            cgpa: 7.5,
            backlogs: 0,
            otherEligibility: "No active backlogs at the time of joining."
          },
          selectionRounds: {
            resumeShortlisting: true,
            prePlacementTalk: true,
            groupDiscussion: false,
            onlineTest: true,
            aptitudeTest: true,
            technicalTest: true,
            technicalInterview: true,
            hrInterview: true,
            otherRounds: true,
            otherRoundsDescription: "System Design Round"
          }
        }
      ],
      applicationDetails: {
        applicationDeadline: "2025-06-15",
        applicationLink: "https://techinnovators.com/apply",
        appliedStudents: [
            {
                studentId: "12212001",
                studentName: "Gaurav Sharma",
                studentEmail: "12214049@nitkkr.ac.in",
                studentBranch: "CSE",
                studentCgpa: 8.5,
                studentBacklogs: 0,
                studentStatus: "APPLIED",
            },
            {
                studentId: "12212002",
                studentName: "Amit Kumar",
                studentEmail: "12214002@nitkkr.ac.in",
                studentBranch: "CSE",
                studentCgpa: 8.0,
                studentBacklogs: 0,
                studentStatus: "APPLIED",
            },
            {
                studentId: "12212003",
                studentName: "Rahul Singh",
                studentEmail: "12212003@nitkkr.ac.in",
                studentBranch: "CSE",
                studentCgpa: 7.5,
                studentBacklogs: 0,
                studentStatus: "APPLIED",
            },
        ],
        appearedStudents: [
            {
                studentId: "12212001",
                studentName: "Gaurav Sharma",
                studentEmail: "12214049@nitkkr.ac.in",
                studentBranch: "CSE",
                studentCgpa: 8.5,
                studentBacklogs: 0,
                studentStatus: "APPLIED",
            },
            {
                studentId: "12212002",
                studentName: "Amit Kumar",
                studentEmail: "12214002@nitkkr.ac.in",
                studentBranch: "CSE",
                studentCgpa: 8.0,
                studentBacklogs: 0,
                studentStatus: "APPLIED",
            },
            {
                studentId: "12212003",
                studentName: "Rahul Singh",
                studentEmail: "12212003@nitkkr.ac.in",
                studentBranch: "CSE",
                studentCgpa: 7.5,
                studentBacklogs: 0,
                studentStatus: "APPLIED",
            },
        ],
        selectedStudents: [],
        rejectedStudents: [],
           
        
      },
      placementType: "FullTime",
      selectedJNF: "65f3a8d9c9b1f7a5b6d2e1f9",
      createdBy: "65f3a8d9c9b1f7a5b6d2e1f0",
      driveStatus: "IN PROGRESS",
      driveMetrics: {
        eligibleStudents: 200,
        appliedStudents: 150,
        appearedStudents: 120,
        selectedStudents: 10,
        rejectedStudents: 110,
        round: 2,
        roundName: "Technical Interview",
        roundType: "OFFLINE"
      },
      roundDetails: {
        rounds: [
          {
            index: 1,
            roundName: "Resume Shortlisting",
            roundType: "ONLINE",
            roundDate: "2025-06-20",
            roundDuration: "1 Hour",
            venue: "Online Platform",
            roundStatus: "COMPLETED",
            appliedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            appearedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            selectedStudents: [],
            rejectedStudents: [],
            results: {
              selectedStudents: [],
              message: "Selected students have cleared this round.",
              notifyStudents: true
            }
          },
          {
            index: 2,
            roundName: "Online Assessment",
            roundType: "OFFLINE",
            roundDate: "2025-06-20",
            roundDuration: "3 Hour",
            venue: "Offline",
            roundStatus: "ONGOING",
            appliedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            appearedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            selectedStudents: [],
            rejectedStudents: [],
            results: {
              selectedStudents: [],
              message: "Selected students have cleared this round.",
              notifyStudents: true
            }
          },
          {
            index: 3,
            roundName: "Technical Interview",
            roundType: "OFFLINE",
            roundDate: "2025-06-20",
            roundDuration: "3 Hour",
            venue: "Offline",
            roundStatus: "UPCOMING",
            appliedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            appearedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            selectedStudents: [],
            rejectedStudents: [],
            results: {
              selectedStudents: [],
              message: "Selected students have cleared this round.",
              notifyStudents: true
            }
          },
          {
            index: 4,
            roundName: "HR Interview",
            roundType: "OFFLINE",
            roundDate: "2025-06-20",
            roundDuration: "3 Hour",
            venue: "Offline",
            roundStatus: "UPCOMING",
            appliedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            appearedStudents: [
                {
                    studentId: "12212001",
                    studentName: "Gaurav Sharma",
                    studentEmail: "12214049@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212002",
                    studentName: "Amit Kumar",
                    studentEmail: "12214002@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 8.0,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
                {
                    studentId: "12212003",
                    studentName: "Rahul Singh",
                    studentEmail: "12212003@nitkkr.ac.in",
                    studentBranch: "CSE",
                    studentCgpa: 7.5,
                    studentBacklogs: 0,
                    studentStatus: "APPLIED",
                },
            ],
            selectedStudents: [],
            rejectedStudents: [],
            results: {
              selectedStudents: [],
              message: "Selected students have cleared this round.",
              notifyStudents: true
            }
          },
        ]
      }
    }
  ];
  
  export default PlacementData;