export const studentQueries = [
    {
        id: 1,
        name: "Aditya Singh",
        email: "aditya@nitkkr.ac.in",
        department: "CSE",
        batch: 2022,
        subject: "Resume Review Process",
        description: "How can I get my resume reviewed by the T&P cell?",
        reply: "",
        reviewed: false,
      },
      {
        id: 2,
        name: "Taanvi Sharma",
        email: "taanvi@nitkkr.ac.in",
        department: "ECE",
        batch: 2023,
        subject: "Mock Interviews",
        description: "Are there mock interview sessions conducted by the T&P cell?",
        reply: "",
        reviewed: false,
      },
      {
        id: 3,
        name: "Aman Verma",
        email: "amanverma@nitkkr.ac.in",
        department: "ME",
        batch: 2024,
        subject: "Skill Development Programs",
        description: "What skill development programs are available for placements?",
        reply: "",
        reviewed: false,
      },
      {
        id: 4,
        name: "Sneha Rao",
        email: "sneharao@nitkkr.ac.in",
        department: "IT",
        batch: 2023,
        subject: "Eligibility Criteria",
        description: "What are the eligibility criteria for participating in campus placements?",
        reply: "",
        reviewed: false,
      },
      {
        id: 5,
        name: "Ravi Sharma",
        email: "ravisharma@nitkkr.ac.in",
        department: "ECE",
        batch: 2025,
        subject: "Placement Drive Schedule",
        description: "Where can I find the schedule for upcoming placement drives?",
        reply: "",
        reviewed: false,
      },
      {
        id: 6,
        name: "Priya Patel",
        email: "priyapatel@nitkkr.ac.in",
        department: "EEE",
        batch: 2023,
        subject: "Certifications and Courses",
        description: "Are there any certifications that can enhance placement chances?",
        reply: "",
        reviewed: false,
      }
    // ...other student queries
  ];
  
  export const recruiterQueries = [
    {
        id: 1,
        company: "Tech Solutions Inc.",
        website: "www.techsolutions.com",
        email: "hr@techsolution.com",
        subject: "Campus Recruitment Procedure",
        description: "What are the steps to initiate campus recruitment at NIT KKR?",
        reply: "",
        reviewed: false,
      },
      {
        id: 2,
        company: "Innovatech Pvt. Ltd.",
        website: "www.innovatech.com",
        email: "hr@innovatech.com",
        subject: "Selection Process",
        description: "How does the T&P cell assist in the selection process of candidates?",
        reply: "",
        reviewed: false,
      },
      {
        id: 3,
        company: "FutureGen Corp.",
        website: "www.futuregen.com",
        email: "contact@futuregen.com",
        subject: "Interview Logistics",
        description: "Can the T&P cell assist with the logistics for conducting interviews?",
        reply: "",
        reviewed: false,
      },
      {
        id: 4,
        company: "Vertex Technologies",
        website: "www.vertextech.com",
        email: "vertex.hr@vertextech.com",
        subject: "Student Profiles",
        description: "How can we access detailed student profiles for recruitment?",
        reply: "",
        reviewed: false,
      },
      {
        id: 5,
        company: "CyberNetics Ltd.",
        website: "www.cybernetics.com",
        email: "hr@cybernetics.com",
        subject: "Internship Programs",
        description: "Can the T&P cell help in recruiting interns for our company?",
        reply: "",
        reviewed: false,
      }
    // ...other recruiter queries
  ];
  